name: CI - Build Test

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - ".npmrc"
      - "next.config.js"
      - "tsconfig.json"
      - "Dockerfile"
      - ".dockerignore"
      - "public/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - ".npmrc"
      - "next.config.js"
      - "tsconfig.json"
      - "Dockerfile"
      - ".dockerignore"
      - "public/**"
      - ".github/workflows/ci.yml"
  workflow_run:
    workflows: ["Infrastructure Deployment"]
    types: [completed]
    branches: [main]

jobs:
  verify-iac:
    if: ${{ github.event_name == 'workflow_run' }}
    runs-on: ubuntu-latest
    outputs:
      should_continue: ${{ steps.check.outputs.should_continue }}
    steps:
      - name: Check if IaC workflow succeeded
        id: check
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "should_continue=true" >> $GITHUB_OUTPUT
          else
            echo "should_continue=false" >> $GITHUB_OUTPUT
          fi

  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    needs: [verify-iac]
    if: |
      github.event_name != 'workflow_run' ||
      needs.verify-iac.outputs.should_continue == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Build
        run: npm run build
