# name: Build, Deploy with Terraform

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# env:
#   PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
#   REGION: ${{ secrets.GCP_REGION }}
#   SERVICE_NAME: mickey-app
#   REPOSITORY: mickey-app-repo

# jobs:
#   terraform-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Google Auth
#         id: auth
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: "${{ secrets.GCP_SA_KEY }}"

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v3

#       - name: Terraform Init
#         run: |
#           cd infrastructure/terraform
#           terraform init

#       - name: Terraform Apply
#         run: |
#           cd infrastructure/terraform
#           terraform apply -auto-approve \
#             -var="project_id=$PROJECT_ID" \
#             -var="region=$REGION"

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

#       - name: Update Cloud Run service with new image
#         run: |
#           cd infrastructure/terraform
#           terraform apply -auto-approve \
#             -var="project_id=$PROJECT_ID" \
#             -var="region=$REGION" \
#             -var="container_image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
